-----> MEIOS DE PAGAMENTO (PRODUÇÃO) <-----
SELECT
  T_DW_D_PAIS_MDM.CD_PAIS,
  T_DW_D_PAIS_MDM.NO_PAIS,
  T_DW_D_PAIS_MDM.NO_UNIDADE_MONETARIA,
  T_DW_F_AGG_PEDIDO_BIO.NM_PEDIDO_MOTOR_BIO,
  T_DW_D_PEDIDO_ATG_BIO.NM_PEDIDO_ATG,
  T_DW_F_AGG_PEDIDO_BIO.DT_CRIACAO_PEDIDO,
  T_DW_D_SITUACAO_PEDIDO_BIO.DC_SITUACAO_PEDIDO,
  T_DW_D_PESSOA_CND.CD_PESSOA,
  T_DW_D_PESSOA_CF.CD_PESSOA
FROM
  T_DW_D_PAIS_MDM,
  T_DW_F_AGG_PEDIDO_BIO,
  T_DW_D_PEDIDO_ATG_BIO,
  T_DW_D_SITUACAO_PEDIDO_BIO,
  T_DW_D_PESSOA_MDM  T_DW_D_PESSOA_CND,
  T_DW_D_PESSOA_MDM  T_DW_D_PESSOA_CF,
  T_DW_D_DATA
WHERE
  ( T_DW_D_SITUACAO_PEDIDO_BIO.CD_SK_SITUACAO_PEDIDO_BIO=T_DW_F_AGG_PEDIDO_BIO.CD_SK_SITUACAO_PEDIDO_BIO  )
  AND  ( T_DW_F_AGG_PEDIDO_BIO.CD_SK_PEDIDO_ATG_BIO=T_DW_D_PEDIDO_ATG_BIO.CD_SK_PEDIDO_ATG_BIO  )
  AND  ( T_DW_F_AGG_PEDIDO_BIO.CD_SK_PESSOA_CF=T_DW_D_PESSOA_CF.CD_SK_PESSOA_MDM  )
  AND  ( T_DW_F_AGG_PEDIDO_BIO.CD_SK_PESSOA_CND=T_DW_D_PESSOA_CND.CD_SK_PESSOA_MDM  )
  AND  ( TO_DATE(TO_CHAR(T_DW_F_AGG_PEDIDO_BIO.DT_CRIACAO_PEDIDO, 'DD/MM/YYYY'), 'DD/MM/YYYY')=T_DW_D_DATA.DT_DATA  )
  AND  ( T_DW_F_AGG_PEDIDO_BIO.CD_SK_PAIS_MDM=T_DW_D_PAIS_MDM.CD_SK_PAIS_MDM  )
  AND  
  (
   T_DW_D_PAIS_MDM.NO_PAIS  IN  ( 'ARGENTINA'  )
   AND
   T_DW_D_DATA.CD_DW_ANO  IN  ( 2016, 2017  )
  )




-----> MEIOS DE PAGAMENTO DEV/HOMOLOGAÇÃO <-----
SELECT
  T_DW_D_PAIS_MDM.CD_PAIS,
  T_DW_D_PAIS_MDM.NO_PAIS,
  T_DW_D_PAIS_MDM.NO_UNIDADE_MONETARIA,
  T_DW_F_AGG_PEDIDO_BIO.NM_PEDIDO_MOTOR_BIO,
  T_DW_D_PEDIDO_ATG_BIO.NM_PEDIDO_ATG,
  T_DW_F_AGG_PEDIDO_BIO.DT_CRIACAO_PEDIDO,
  T_DW_D_SITUACAO_PEDIDO_BIO.DC_SITUACAO_PEDIDO,
  T_DW_D_PESSOA_CND.CD_PESSOA,
  T_DW_D_PESSOA_CF.CD_PESSOA
FROM
  T_DW_D_PAIS_MDM,
  T_DW_F_AGG_PEDIDO_BIO,
  T_DW_D_PEDIDO_ATG_BIO,
  T_DW_D_SITUACAO_PEDIDO_BIO,
  T_DW_D_PESSOA_MDM  T_DW_D_PESSOA_CND,
  T_DW_D_PESSOA_MDM  T_DW_D_PESSOA_CF,
  T_DW_D_DATA
WHERE
  ( T_DW_D_SITUACAO_PEDIDO_BIO.CD_SK_SITUACAO_PEDIDO_BIO=T_DW_F_AGG_PEDIDO_BIO.CD_SK_SITUACAO_PEDIDO_BIO  )
  AND  ( T_DW_F_AGG_PEDIDO_BIO.CD_SK_PEDIDO_ATG_BIO=T_DW_D_PEDIDO_ATG_BIO.CD_SK_PEDIDO_ATG_BIO  )
  AND  ( T_DW_F_AGG_PEDIDO_BIO.CD_SK_PESSOA_CF=T_DW_D_PESSOA_CF.CD_SK_PESSOA_MDM  )
  AND  ( T_DW_F_AGG_PEDIDO_BIO.CD_SK_PESSOA_CND=T_DW_D_PESSOA_CND.CD_SK_PESSOA_MDM  )
  AND  ( TO_DATE(TO_CHAR(T_DW_F_AGG_PEDIDO_BIO.DT_CRIACAO_PEDIDO, 'DD/MM/YYYY'), 'DD/MM/YYYY')=T_DW_D_DATA.DT_DATA  )
  AND  ( T_DW_F_AGG_PEDIDO_BIO.CD_SK_PAIS_MDM=T_DW_D_PAIS_MDM.CD_SK_PAIS_MDM  )
  AND  
  (
   T_DW_D_DATA.CD_DW_ANO  IN  ( 2016, 2017  )
   AND
   T_DW_D_PAIS_MDM.NO_PAIS  IN  ( 'ARGENTINA'  )
  )
