-----> GESTÃO COMERCIAL (PRODUÇÃO) <-----
SELECT
  T_DW_D_PAIS_MDM.CD_PAIS,
  T_DW_D_PAIS_MDM.NO_PAIS,
  T_DW_D_PAIS_MDM.NO_UNIDADE_MONETARIA,
  SISDMPM.T_DW_F_PEDIDO_BIO.NM_PEDIDO_MOTOR_BIO,
  SISDMPM.T_DW_D_PEDIDO_ATG_BIO.NM_PEDIDO_ATG,
  SISDMPM.T_DW_F_PEDIDO_BIO.CD_SK_DT_CAPTACAO_PEDIDO,
  T_DW_D_PESSOA__MDM.CD_PESSOA,
  T_DW_D_PESSOA_MDM_COMPRA.CD_PESSOA
FROM
  SISDMPM.T_DW_F_PEDIDO_BIO,
  T_DW_D_PAIS_MDM,
  SISDMPM.T_DW_D_PEDIDO_ATG_BIO,
  SISDMPM.T_DW_D_PESSOA_MDM  T_DW_D_PESSOA__MDM,
  SISDMPM.T_DW_D_PESSOA_MDM  T_DW_D_PESSOA_MDM_COMPRA,
  SISDMPM.T_DW_D_DATA
WHERE
  ( SISDMPM.T_DW_D_PEDIDO_ATG_BIO.CD_SK_PEDIDO_ATG_BIO=SISDMPM.T_DW_F_PEDIDO_BIO.CD_SK_PEDIDO_ATG_BIO  )
  AND  ( SISDMPM.T_DW_F_PEDIDO_BIO.CD_SK_DT_CAPTACAO_PEDIDO=SISDMPM.T_DW_D_DATA.DT_DATA  )
  AND  ( SISDMPM.T_DW_F_PEDIDO_BIO.CD_SK_PESSOA_COMPRA=T_DW_D_PESSOA_MDM_COMPRA.CD_SK_PESSOA_MDM  )
  AND  ( SISDMPM.T_DW_F_PEDIDO_BIO.CD_SK_PESSOA_VENDA=T_DW_D_PESSOA__MDM.CD_SK_PESSOA_MDM  )
  AND  ( SISDMPM.T_DW_F_PEDIDO_BIO.CD_SK_PAIS_MDM=T_DW_D_PAIS_MDM.CD_SK_PAIS_MDM  )
  AND  
  (
   T_DW_D_PAIS_MDM.NO_PAIS  IN  ( 'ARGENTINA'  )
   AND
   SISDMPM.T_DW_D_DATA.CD_DW_ANO  IN  ( 2016, 2017  )
  )



-----> GESTÃO COMERCIAL DEV/HOMOLOGAÇÃO <-----
SELECT
  T_DW_D_PAIS_MDM.CD_PAIS,
  T_DW_D_PAIS_MDM.NO_PAIS,
  T_DW_D_PAIS_MDM.NO_UNIDADE_MONETARIA,
  SISDMPM.T_DW_F_PEDIDO_BIO.NM_PEDIDO_MOTOR_BIO,
  SISDMPM.T_DW_D_PEDIDO_ATG_BIO.NM_PEDIDO_ATG,
  SISDMPM.T_DW_F_PEDIDO_BIO.CD_SK_DT_CAPTACAO_PEDIDO,
  T_DW_D_PESSOA__MDM.CD_PESSOA,
  T_DW_D_PESSOA_MDM_COMPRA.CD_PESSOA
FROM
  SISDMPM.T_DW_F_PEDIDO_BIO,
  T_DW_D_PAIS_MDM,
  SISDMPM.T_DW_D_PEDIDO_ATG_BIO,
  SISDMPM.T_DW_D_PESSOA_MDM  T_DW_D_PESSOA__MDM,
  SISDMPM.T_DW_D_PESSOA_MDM  T_DW_D_PESSOA_MDM_COMPRA,
  SISDMPM.T_DW_D_DATA
WHERE
  ( SISDMPM.T_DW_D_PEDIDO_ATG_BIO.CD_SK_PEDIDO_ATG_BIO=SISDMPM.T_DW_F_PEDIDO_BIO.CD_SK_PEDIDO_ATG_BIO  )
  AND  ( SISDMPM.T_DW_F_PEDIDO_BIO.CD_SK_DT_CAPTACAO_PEDIDO=SISDMPM.T_DW_D_DATA.DT_DATA  )
  AND  ( SISDMPM.T_DW_F_PEDIDO_BIO.CD_SK_PESSOA_COMPRA=T_DW_D_PESSOA_MDM_COMPRA.CD_SK_PESSOA_MDM  )
  AND  ( SISDMPM.T_DW_F_PEDIDO_BIO.CD_SK_PESSOA_VENDA=T_DW_D_PESSOA__MDM.CD_SK_PESSOA_MDM  )
  AND  ( SISDMPM.T_DW_F_PEDIDO_BIO.CD_SK_PAIS_MDM=T_DW_D_PAIS_MDM.CD_SK_PAIS_MDM  )
  AND  
  (
   T_DW_D_PAIS_MDM.NO_PAIS  IN  ( 'ARGENTINA'  )
   AND
   SISDMPM.T_DW_D_DATA.CD_DW_ANO  IN  ( 2016, 2016  )
  )
